blog-elasticsearch:
  container_name: blog-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/blog/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
blog-postgresql:
  container_name: blog-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/blog/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=blog
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
